#! /bin/bash
set -e
echo "update and upgrade"
apt-get -y update
apt-get -y upgrade
add-apt-repository ppa:puredyne-team/ppa
add-apt-repository ppa:openstudio/stable
apt-key add key.txt
dpkg -i tangostudio-*.deb
dpkg -i openstudio*.deb
#apt-get -y install openstudio-apt
apt-get install medibuntu-keyring
apt-get -y update
apt-get -y --force-yes upgrade
#installing JACK
apt-get -y install jackd
#installing multimedia codecs
apt-get -y install ubuntu-restricted-extras
#install meta
apt-get -y install openstudio-admin openstudio-desktop openstudio-djing openstudio-drums openstudio-fluxbox openstudio-graphics \
openstudio-guitar openstudio-jack openstudio-looping openstudio-midi openstudio-mixing openstudio-multimedia openstudio-musicnotation  \
openstudio-musiciantools openstudio-plugins-dssi openstudio-plugins-ladspa openstudio-plugins-lv2 openstudio-realtime openstudio-recording \
openstudio-timestretching openstudio-samplers openstudio-soundsynthesis openstudio-synths
#rm not needed packages
apt-get -y purge  computer-janitor computer-janitor-gtk gnome-games-common gbrainy evolution
#adduser openstudio audio
apt-get -y install openstudio-swappiness openstudiomenu
cd ..
rm -r confopenstudio
cd
exit
exit
cd
