#! /bin/bash
set -e
apt-get -y update
apt-get -y upgrade
apt-get -y install git-core
cp /etc/apt/sources.list /etc/apt/sources.list_bak
git clone git@github.com:johnsen/confopenstudio.git
cd confopenstudio/
mv sources.list.openstudiopro /etc/apt/sources.list
apt-get -y update
apt-get -y upgrade
#kernels key
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F141B61E
#puredyne key
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 79696851 
#openstudio10 key
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EBE5EE7C   
apt-key add key.txt
apt-get -y update
apt-get -y upgrade
apt-get -y install jackd
apt-get -y remove  computer-janitor computer-janitor-gtk 
apt-get -y install ubuntu-restricted-extras
exit
