#! /bin/bash
#http://www.jeffsplace.net/node/12
set -e
dpkg-divert --add --divert /usr/lib/gstreamer-0.10/libgstpulse.so.ubuntu --rename /usr/lib/gstreamer-0.10/libgstpulse.so
dpkg-divert --add --divert /usr/bin/pulseaudio.ubuntu --rename /usr/bin/pulseaudio
sh -c 'echo '\''#!/bin/sh'\'' > /usr/bin/pulseaudio'
chmod a+x /usr/bin/pulseaudio
#gstreamer-properties
#and set everything from PulseAudio to ALSA.
dpkg -i libsdl1.2debian-pulseaudio-dummy_1.0_all.deb
apt-get install libsdl1.2debian-all



apt-get remove indicator-sound
